### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by efpapado** [esolitos/drush-resave-nodes#3]
Is the .gitignore really needed? And it is set to ignore `actions/` !!

**Comment by esolitos** [comment]
[Read my comment about this in a pull-request.](https://github.com/esolitos/drush-resave-nodes/pull/2#discussion-diff-57560946)
I see the `actions/` directory a "working directory", where most things are not going to git, don't you think?
In the end it's just a matter of doing `git add -f` if we really want to track something there.
